spring:
  h2:
    console:
      enabled: true

server:
  port: 9001


app:
  accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInNjb3BlIjpbInNlcnZlciIsInBheW1lbnRzIiwicHJvZmlsZXMiLCJhY2NvdW50cyIsInRyYW5zYWN0aW9ucyIsInBheW1lbnQtc3VibWlzc2lvbnMiXSwiZXhwIjozNjc3NTA5NTY2LCJhdXRob3JpdGllcyI6WyJST0xFX1RSVVNURURfQ0xJRU5UIiwiUk9MRV9DTElFTlQiXSwianRpIjoiZmNiZGVmMDAtZjRkNy00YmI2LWE1NmQtOTc5NzlmYTIxZTVhIiwiY2xpZW50X2lkIjoiS1ZPVUNSMmhURnlzMkdoYk1oTE4ifQ.Lamjyagpi1AFV2bvUrEXXsGq4NsErMn-HCkb_avGqHiGYsUKjOHnfi7EyNLhdtc8A0dDYO3XyYRX8V8nsGDCCuhQetCxQ2756WLcU2Ng3m6Kt4ClGe7Ot1zuX4wAQvBLByh5DC0x3mSP3Z9MweRKreS6l2aSA4tQjB8WnRldx0w
