spring:
  h2:
    console:
      enabled: true

server:
  port: 9001


app:
  accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInNjb3BlIjpbInNlcnZlciIsInBheW1lbnRzIiwicHJvZmlsZXMiLCJhY2NvdW50cyIsInRyYW5zYWN0aW9ucyIsInBheW1lbnQtc3VibWlzc2lvbnMiXSwiZXhwIjozNjc3Njc0MjQzLCJhdXRob3JpdGllcyI6WyJST0xFX1RSVVNURURfQ0xJRU5UIiwiUk9MRV9DTElFTlQiXSwianRpIjoiMDg4MzYyYmItOGMyNC00M2EwLWJhMDctNDc4ZTJlMzNiM2I0IiwiY2xpZW50X2lkIjoiUEpqWHNwU2tyeElsNm5TYVQ5d0wifQ.mZ7AYOj9tEV3H3bGY8bqoPSETD6bDyItuOdbbi4JuUA3Fp3cQNOiEopSlUh7eyDIt6hcRELXDvFh9F3B3TPvcQK2qBbo0U-RIN266_GqigtvODMbdNiGsez1KCE9J7nQKwd7kvsYtAISJr06v3zUVw-tsHEiiOulUMw18l7szY8
  accessTokenPaymentSubmission: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInVzZXJfbmFtZSI6Ijk0NDcyNjY4NDciLCJzY29wZSI6WyJzZXJ2ZXIiLCJwYXltZW50cyIsInByb2ZpbGVzIiwiYWNjb3VudHMiLCJ0cmFuc2FjdGlvbnMiLCJwYXltZW50LXN1Ym1pc3Npb25zIl0sImV4cCI6MzY3NzY3NDM1NiwiYXV0aG9yaXRpZXMiOlsiVVNFUiIsIlJPTEVfQ0xJRU5UIl0sImp0aSI6Ijk4Mjk4YzgyLTAxN2ItNDA2MS05YzYyLTRhMDZkNGUyZDA0MSIsImNsaWVudF9pZCI6IlBKalhzcFNrcnhJbDZuU2FUOXdMIn0.E3cfAWYM4j9wKLr3Gk9P3NNCF0sl2SsoC-sjy3qweE78ETBOOegpqwUt7Pz3DesN9lQrhKOP5phMtGqAPrujxc7zGTt-VXQauJI9vuVF-eHAsp2EhQVs6JyP3Lr5LECA3QtC8LdIjr4qTPnqGgtkkcmInFl_QsVoNg2qX1e316M